//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFaceInfo
    {
        public string username { get; set; }
        public byte[] faceSample { get; set; }
        public int userId { get; set; }
        public int id { get; set; }
        public string tag { get; set; }
    }
}
